spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/time_db
    username: postgres
    password: password
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 5
      minimum-idle: 2
